apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - name: welcome-container
          image: shrijadhanalakshmi/project1:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-service
spec:
  type: NodePort
  selector:
    app: welcome-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
